# Generated by Django 4.1.9 on 2023-05-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0003_alter_rudeusers_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_daily_pnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateField(default=None)),
                ('daily_pnl', models.FloatField(default=None)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userauth.rudeusers')),
            ],
        ),
    ]
