# Generated by Django 4.1.9 on 2023-08-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
