# Generated by Django 4.1.9 on 2023-05-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0002_alter_rudeusers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userauth.rudeusers')),
            ],
        ),
    ]
