# Generated by Django 4.1.9 on 2023-05-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='entry_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='entry_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='entry_reason',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='exit_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='exit_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='follow_setup',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='market',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='pnl',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='quantity',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='symbol',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='trade_note',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='action',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
