# Generated by Django 4.1.9 on 2023-08-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtrade', '0002_usersdata_entry_datetime_usersdata_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='trade_rating',
            field=models.IntegerField(default=None),
        ),
    ]
