# Generated by Django 4.1.9 on 2023-08-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtrade', '0005_alter_user_daily_pnl_entry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_daily_pnl',
            name='entry_datetime',
            field=models.DateField(default=None),
        ),
    ]
