# Generated by Django 4.1.9 on 2023-05-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rudeusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
