# Generated by Django 4.1.9 on 2023-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_rudeusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rudeusers',
            name='country',
            field=models.CharField(default='USD', max_length=25),
        ),
    ]
